# Generated by Django 3.2.7 on 2021-09-19 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=False)),
                ('user', models.TextField(default='')),
                ('name', models.TextField(max_length=50)),
                ('polygon', models.TextField(default='')),
                ('companies', models.TextField(default='')),
                ('status', models.BooleanField(default=False)),
                ('image', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('lines', models.TextField(default='')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citymngmt.city')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField(default='')),
                ('name', models.TextField(max_length=50)),
                ('stops', models.TextField(default='')),
                ('zone_times', models.TextField(default='')),
                ('status', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citymngmt.company')),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('subtitle', models.TextField(default='')),
                ('address', models.TextField(default='')),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citymngmt.line')),
            ],
        ),
    ]
