# Generated by Django 3.2.7 on 2021-09-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0003_alter_city_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='user_id',
            new_name='user',
        ),
    ]
