# Generated by Django 3.2.7 on 2021-09-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0006_rename_name_company_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='companies',
        ),
    ]
