# Generated by Django 3.2.7 on 2021-09-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0014_company_activated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='password',
        ),
    ]
