# Generated by Django 3.2.7 on 2021-09-22 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0019_auto_20210921_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='zone',
            new_name='zone_times',
        ),
    ]
