# Generated by Django 3.2.7 on 2021-09-23 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0022_auto_20210923_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='citymngmt.companyrelations'),
        ),
    ]
