# Generated by Django 3.2.7 on 2021-09-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0025_alter_city_polygon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='return_trip',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='round_trip',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='special_return_trip',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='special_round_trip',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='stops',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='zone_times',
            field=models.JSONField(null=True),
        ),
    ]
