# Generated by Django 3.2.7 on 2021-09-25 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0028_auto_20210924_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='city',
        ),
        migrations.RemoveField(
            model_name='line',
            name='company',
        ),
        migrations.AddField(
            model_name='line',
            name='relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='citymngmt.companyrelations'),
        ),
    ]
