# Generated by Django 3.2.8 on 2021-10-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0035_auto_20211011_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='color',
            field=models.TextField(default='#30b618'),
        ),
    ]
