# Generated by Django 3.2.8 on 2021-10-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0037_alter_city_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, upload_to='city_images/'),
        ),
    ]
