# Generated by Django 3.2.8 on 2021-10-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0038_alter_city_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='municipality_image',
            field=models.ImageField(blank=True, upload_to='city_images/'),
        ),
    ]
