# Generated by Django 3.2.8 on 2021-10-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0039_city_municipality_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='city',
            name='municipality_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
