# Generated by Django 3.2.8 on 2021-10-28 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0043_alter_city_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='Company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='citymngmt.company'),
        ),
        migrations.AddField(
            model_name='line',
            name='color',
            field=models.TextField(default='#30b618'),
        ),
    ]
