# Generated by Django 3.2.8 on 2021-10-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0044_auto_20211028_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='Company',
            new_name='company',
        ),
    ]
