# Generated by Django 3.2.8 on 2021-11-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0048_auto_20211030_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='position',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
