# Generated by Django 3.2.9 on 2021-12-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0050_auto_20211213_1200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusStops',
            new_name='BusStop',
        ),
    ]
