# Generated by Django 3.2.7 on 2021-09-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='user',
        ),
        migrations.AddField(
            model_name='city',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
