# Generated by Django 3.2.7 on 2021-09-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0007_remove_city_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='lines',
        ),
    ]
