# Generated by Django 3.2.7 on 2021-09-21 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0009_clientuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='citymngmt.clientuser')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='citymngmt.company')),
            ],
        ),
    ]
