# Generated by Django 3.2.7 on 2021-09-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0013_companyrelations_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
