# Generated by Django 3.2.7 on 2021-09-21 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0017_line_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='color',
        ),
    ]
