# Generated by Django 3.2.7 on 2021-09-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0023_busstop_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstop',
            name='line',
        ),
        migrations.AddField(
            model_name='busstop',
            name='lines',
            field=models.TextField(default=''),
        ),
    ]
