# Generated by Django 3.2.7 on 2021-09-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0024_auto_20210923_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='polygon',
            field=models.JSONField(null=True),
        ),
    ]
