# Generated by Django 3.2.7 on 2021-09-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0026_auto_20210924_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusStop',
            new_name='BusStops',
        ),
    ]
