# Generated by Django 3.2.7 on 2021-09-25 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0029_auto_20210924_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='citymngmt.city'),
        ),
    ]
