# Generated by Django 3.2.7 on 2021-09-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0030_line_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='schedule',
            field=models.JSONField(null=True),
        ),
    ]
