# Generated by Django 3.2.7 on 2021-09-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citymngmt', '0033_alter_city_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='emergency_phone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
